### ISSUE TITLE
Py2 branch?

### ISSUE THREAD

**Issue by Chris2048** [rancher/client-python#7]
When I try master HEAD, there is a difference in functionality on py2 vs py3 (I cannot see 'environments' in a project dict).

But If I revert to https://raw.githubusercontent.com/rancher/client-python/8fc5cd7c6306a51dbe9fb55400632268b7a34374/rancher.py this works - it seems py2 compat was lost at this point; Can it (dual compat) be restored?

It seems there was a commit "Update to python 3" that removed six compat from master - can this stuff remain on a py2 branch in that case?

**Comment by dramich** [comment]
Hey @Chris2048, we no longer support python2 which is why it was removed with no plans to add it back.
